btre/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

# global urls
urlpatterns = [
    path("", include("pages.urls", namespace="pages")),  # for pages app
    path("accounts/", include("accounts.urls", namespace="accounts")),  # for accounts app
    path("listings/", include("listings.urls", namespace="listings")),  # for listings app
    path("contacts/", include("contacts.urls")),  # for contacts app
    path("notification/", include("notification.urls")),  # for notification app
    path("admin/", admin.site.urls),  # for django admin
    path("accounts/", include("django.contrib.auth.urls")),  # for django auth
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # for media files

listings/urls.py
from django.urls import path
from . import views

# Define the application namespace
app_name = "listings"

# URL patterns for the listings app
urlpatterns = [
    # URL pattern for the index view, which displays all listings
    path("", views.index, name="listings"),
    
    # URL pattern for the listing view, which displays a specific listing by its ID
    path("<int:listing_id>/", views.listing, name="listing"),
    
    # URL pattern for the search view, which allows users to search for listings
    path("search/", views.search, name="search"),
]

pages/urls.py
from django.urls import path
from . import views


app_name = "pages"
urlpatterns = [
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
    
]

templates/pages/about.html
{% extends 'layout.html' %} 

{% load static %}

{% block title %} {{ block.super }} | About {% endblock %}

{% block content %}
<section id="showcase-inner" class="py-5 text-white">
    <div class="container">
      <div class="row text-center">
        <div class="col-md-12">
          <h1 class="display-4">About BT Real Estate</h1>
          <p class="lead">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sunt, pariatur!</p>
        </div>
      </div>
    </div>
  </section>

  <!-- Breadcrumb -->
  <section id="bc" class="mt-3">
    <div class="container">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="{% url 'pages:index' %}">
              <i class="fas fa-home"></i> Home</a>
          </li>
          <li class="breadcrumb-item active"> About</li>
        </ol>
      </nav>
    </div>
  </section>

  <section id="about" class="py-4">
    <div class="container">
      <div class="row">
        <div class="col-md-8">
          <h2>We Search For The Perfect Home</h2>
          <p class="lead">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sunt, pariatur!</p>
          <img src="{% static 'img/about.jpg' %}" alt="">
          <p class="mt-4">Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis esse officia repudiandae ad saepe ex, amet
            neque quod accusamus rem quia magnam magni dolorum facilis ullam minima perferendis? Exercitationem at quaerat
            commodi id libero eveniet harum perferendis laborum molestias quia.</p>
        </div>
        <div class="col-md-4">
          {% if mvp_realtors %}
            {% for realtor in mvp_realtors %}
            <div class="card">
                <img class="card-img-top" src="{{ realtor.photo.url }}" alt="Seller of the month">
                <div class="card-body">
                  <h5 class="card-title">Seller Of The Month</h5>
                  <h6 class="text-secondary">{{ realtor.name }}</h6>
                  <p class="card-text">{{ realtor.description }}
                  </p>
                </div>
              </div>
            {% endfor %}
          {% endif %}
        </div>
      </div>
    </div>
  </section>

  <!-- Work -->
  <section id="work" class="bg-dark text-white text-center">
    <h2 class="display-4">We Work For You</h2>
    <h4>Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem velit aperiam, unde aliquid at similique!</h4>
    <hr>
    <a href="{% url 'listings:listings' %}" class="btn btn-secondary text-white btn-lg">View Our Featured Listings</a>
  </section>

  <!-- Team -->
  <section id="team" class="py-5">
    <div class="container">
      <h2 class="text-center">Our Team</h2>
      <div class="row text-center">
        {% if realtors %}
          {% for realtor in realtors %}
          <div class="col-md-4">
                <img src="{{ realtor.photo.url }}" alt="" class="rounded-circle mb-3" style="border-radius: 50%; width: 100px; height: 100px;">
              <h4>{{ realtor.name }}</h4>
              <p class="text-success">
                <i class="fas fa-award text-success mb-3"></i> Realtor</p>
              <hr>
              <p>
                <i class="fas fa-phone"></i> {{ realtor.phone }}</p>
              <p>
                <i class="fas fa-envelope-open"></i> {{ realtor.email }}</p>
            </div>
          {% endfor %}
        {% else %}
          <div class="col-md-12">
            <p>No Realtors Available</p>
          </div>
        {% endif %}       
      </div>
    </div>
  </section>
{% endblock %}

templates/pages/index.html
{% extends 'layout.html' %} 

{% load humanize %}

{% block title %} {{ block.super }} | Welcome {% endblock %}

{% block content %}
<!-- Showcase -->
<section id="showcase">
    <div class="container text-center">
      <div class="home-search p-5">
        <div class="overlay p-5">
          <h1 class="display-4 mb-4">
            Property Searching Just Got So Easy
          </h1>
          <p class="lead">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae quas, asperiores eveniet vel nostrum magnam
            voluptatum tempore! Consectetur, id commodi!</p>
          <div class="search">
            <form action="{% url 'listings:search' %}">
              <!-- Form Row 1 -->
              <div class="form-row">
                <div class="col-md-4 mb-3">
                  <label class="sr-only">Keywords</label>
                  <input type="text" name="keywords" class="form-control" placeholder="Keyword (Pool, Garage, etc)">
                </div>

                <div class="col-md-4 mb-3">
                  <label class="sr-only">City</label>
                  <input type="text" name="city" class="form-control" placeholder="City">
                </div>

                <div class="col-md-4 mb-3">
                  <label class="sr-only">State</label>
                  <select name="state" class="form-control">
                    <option selected="true" disabled="disabled">State (All)</option>
                    {% for key,value in state_choices.items %}
                      <option value="{{ key }}">{{ value }}</option>
                    {% endfor %}
                  </select>
                </div>
              </div>
              <!-- Form Row 2 -->
              <div class="form-row">
                <div class="col-md-6 mb-3">
                  <label class="sr-only">Bedrooms</label>
                  <select name="bedrooms" class="form-control">
                    <option selected="true" disabled="disabled">Bedrooms (All)</option>
                    {% for key,value in bedroom_choices.items %}
                      <option value="{{ key }}">{{ value }}</option>
                    {% endfor %}
                  </select>
                </div>
                <div class="col-md-6 mb-3">
                  <select name="price" class="form-control" id="type">
                    <option selected="true" disabled="disabled">Max Price (Any)</option>
                    {% for key,value in price_choices.items %}
                      <option value="{{ key }}">{{ value }}</option>
                    {% endfor %}
                  </select>
                </div>
              </div>
              <button class="btn btn-secondary btn-block mt-4" type="submit">Submit form</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
<br>


  <!-- Listings -->
  <section id="listings" class="py-5">
    <div class="container">
      <h3 class="text-center mb-3">Latest Listings</h3>
      <div class="row">
        {% if listings %}
          {% for listing in listings %}
            <!-- Listing 1 -->
            <div class="col-md-6 col-lg-4 mb-4">
              <div class="card listing-preview">
                <img class="card-img-top" src="{{ listing.photo_main.url }}" alt="">
                <div class="card-img-overlay">
                  <h2>
                    <span class="badge badge-secondary text-white">&#8358;{{ listing.price | intcomma }}</span>
                  </h2>
                </div>
                <div class="card-body">
                  <div class="listing-heading text-center">
                    <h4 class="text-primary">{{ listing.title }}</h4>
                    <p>
                      <i class="fas fa-map-marker text-secondary"></i> {{ listing.city }} {{ listing.state }}, {{ listing.zipcode }}</p>
                  </div>
                  <hr>
                  <div class="row py-2 text-secondary">
                    <div class="col-6">
                      <i class="fas fa-th-large"></i> Sqft: {{ listing.sqft }}</div>
                    <div class="col-6">
                      <i class="fas fa-car"></i> Garage: {{ listing.garage }}</div>
                  </div>
                  <div class="row py-2 text-secondary">
                    <div class="col-6">
                      <i class="fas fa-bed"></i> Bedrooms: {{ listing.bedrooms }}</div>
                    <div class="col-6">
                      <i class="fas fa-bath"></i> Bathrooms: {{ listing.bathrooms }}</div>
                  </div>
                  <hr>
                  <div class="row py-2 text-secondary">
                    <div class="col-6">
                      <i class="fas fa-user"></i> {{ listing.realtor }}</div>
                  </div>
                  <div class="row text-secondary pb-2">
                    <div class="col-6">
                      <i class="fas fa-clock"></i> {{ listing.list_date | timesince }}</div>
                  </div>
                  <hr>
                  <a href="{% url 'listings:listing' listing.id %}" class="btn btn-primary btn-block">More Info</a>
                </div>
              </div>
            </div>
          {% endfor %}
        {% else %}
          <div class="col-md-12">
            <p>No Listings Available</p>
          </div>
        {% endif %}

      </div>
    </div>
  </section>

  <section id="services" class="py-5 bg-secondary text-white">
    <div class="container">
      <div class="row text-center">
        <div class="col-md-4">
          <i class="fas fa-comment fa-4x mr-4"></i>
          <hr>
          <h3>Consulting Services</h3>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt, debitis nam! Repudiandae, provident iste consequatur
            hic dignissimos ratione ea quae.</p>
        </div>
        <div class="col-md-4">
          <i class="fas fa-home fa-4x mr-4"></i>
          <hr>
          <h3>Propery Management</h3>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt, debitis nam! Repudiandae, provident iste consequatur
            hic dignissimos ratione ea quae.</p>
        </div>
        <div class="col-md-4">
          <i class="fas fa-suitcase fa-4x mr-4"></i>
          <hr>
          <h3>Renting & Selling</h3>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt, debitis nam! Repudiandae, provident iste consequatur
            hic dignissimos ratione ea quae.</p>
        </div>
      </div>
    </div>
  </section>
{% endblock %}